# Generated by Django 5.2.1 on 2025-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_staffuser_last_login_time_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
