# Generated by Django 5.2.1 on 2025-05-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role'),
        ),
    ]
