# Generated by Django 5.2.1 on 2025-05-10 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_staffuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('total_price', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('financier_confirm', models.BooleanField(default=False)),
                ('financier_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('gip_confirm', models.BooleanField(default=False)),
                ('gip_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('financier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financed_projects', to=settings.AUTH_USER_MODEL)),
                ('project_gip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gip_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
    ]
