# Generated by Django 5.2.1 on 2025-05-19 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_project_financier_alter_project_project_gip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFinancePart',
            fields=[
                ('fs_part_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fs_part_no', models.CharField(max_length=50)),
                ('fs_part_name', models.CharField(max_length=255)),
                ('fs_part_price', models.BigIntegerField()),
                ('fs_start_date', models.DateField()),
                ('fs_finish_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('send_to_tech_dir', models.BooleanField(default=False)),
                ('send_to_tech_dir_date', models.DateTimeField(blank=True, null=True)),
                ('tech_dir_confirm', models.BooleanField(default=False)),
                ('tech_dir_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fin_parts', to=settings.AUTH_USER_MODEL)),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_parts', to='api.project')),
            ],
            options={
                'verbose_name': 'Project Finance Part',
                'verbose_name_plural': 'Project Finance Parts',
                'db_table': 'pro_fin_part',
            },
        ),
    ]
