# Generated by Django 5.2.1 on 2025-05-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_projectfinancepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinancepart',
            name='fs_part_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
