# Generated by Django 5.2.1 on 2025-05-21 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_projectfinancepart_fs_part_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='api.department'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_code', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=500)),
                ('partner_inn', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners',
            },
        ),
    ]
