# Generated by Django 5.2.1 on 2025-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_department_parent_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
