# Generated by Django 5.2.1 on 2025-05-21 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_partner_partner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Unique identifier for the text (e.g., 'create_project_admin')", max_length=100, unique=True)),
                ('en', models.CharField(blank=True, help_text='English translation', max_length=250, null=True)),
                ('ru', models.CharField(blank=True, help_text='Russian translation', max_length=250, null=True)),
                ('uz', models.CharField(blank=True, help_text='Uzbek translation', max_length=250, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('translated_by', models.ForeignKey(blank=True, help_text='The staff user who last updated this translation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'db_table': 'app_internalization',
                'ordering': ['key'],
            },
        ),
    ]
