# Generated by Django 5.2.1 on 2025-05-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_department_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.partner'),
        ),
    ]
