# Generated by Django 5.2.1 on 2025-05-24 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_project_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseType',
            fields=[
                ('phase_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_refusal', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bosqich turi',
                'verbose_name_plural': 'Bosqich turlari',
                'db_table': 'project_phase_types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh yoki rad etish sababi')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Bosqich sanasi')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Rad etish ko‘rib chiqildimi?')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Qachon qabul qilindi?')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_refusals', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan ko‘rib chiqildi?')),
                ('notify_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases_to_respond', to=settings.AUTH_USER_MODEL, verbose_name='Kimga xabar yuboriladi')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_project_phases', to=settings.AUTH_USER_MODEL, verbose_name='Bosqichni bajargan foydalanuvchi')),
                ('phase_type', models.ForeignKey(db_column='phase_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.phasetype', verbose_name='Bosqich turi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha bosqichi',
                'verbose_name_plural': 'Loyiha bosqichlari',
                'db_table': 'project_phases',
                'ordering': ['-performed_at'],
            },
        ),
    ]
