# Generated by Django 5.2.1 on 2025-05-24 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_phasetype_projectphase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasetype',
            options={'ordering': ['order'], 'verbose_name': 'Phase Type', 'verbose_name_plural': 'Phase Types'},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ['-performed_at'], 'verbose_name': 'Project Phase', 'verbose_name_plural': 'Project Phases'},
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_refusals', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment or Reason'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='is_acknowledged',
            field=models.BooleanField(default=False, verbose_name='Acknowledged?'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='notify_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases_to_respond', to=settings.AUTH_USER_MODEL, verbose_name='Notify To'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Performed At'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_project_phases', to=settings.AUTH_USER_MODEL, verbose_name='Performed By'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase_type',
            field=models.ForeignKey(db_column='phase_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.phasetype', verbose_name='Phase Type'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.project', verbose_name='Project'),
        ),
    ]
