# Generated by Django 5.2.1 on 2025-05-27 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_phasetype_options_alter_projectphase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGipPart',
            fields=[
                ('tch_part_code', models.AutoField(primary_key=True, serialize=False)),
                ('tch_part_no', models.CharField(max_length=50)),
                ('tch_part_name', models.CharField(max_length=255)),
                ('tch_part_nach', models.BigIntegerField()),
                ('tch_start_date', models.DateField()),
                ('tch_finish_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('nach_otd_confirm', models.BooleanField(default=False)),
                ('create_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gip_parts', to=settings.AUTH_USER_MODEL)),
                ('fs_part_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gip_parts', to='api.projectfinancepart')),
            ],
            options={
                'verbose_name': 'Technical Part',
                'verbose_name_plural': 'Technical Parts',
                'db_table': 'project_gip_parts',
            },
        ),
    ]
