# Generated by Django 5.2.1 on 2025-05-28 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_projectgippart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgippart',
            name='tch_part_nach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tech_parts', to=settings.AUTH_USER_MODEL),
        ),
    ]
