# Generated by Django 5.2.1 on 2025-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_projectgippart_tch_part_nach'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgippart',
            name='nach_otd_confirm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
