# Generated by Django 5.2.1 on 2025-05-31 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_projectgippart_nach_otd_confirm_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('wo_id', models.AutoField(primary_key=True, serialize=False)),
                ('wo_no', models.IntegerField()),
                ('wo_name', models.CharField(max_length=255)),
                ('wo_start_date', models.DateField()),
                ('wo_finish_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('staff_confirm', models.BooleanField(default=False)),
                ('wo_answer', models.TextField(blank=True, null=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('wo_remark', models.TextField(blank=True, null=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('tch_part_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='api.projectgippart')),
                ('wo_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'db_table': 'work_orders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Максимальный размер файла: 10 МБ', upload_to='work_orders/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.workorder')),
            ],
        ),
    ]
