# Generated by Django 5.2.1 on 2025-05-31 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_workorder_workorderfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_id', models.CharField(help_text='Hierarchical full identifier', max_length=255)),
                ('path_type', models.CharField(help_text='Type: PROJECT, FIN_PART, TECH_PART, WORK_ORDER', max_length=50)),
                ('action', models.CharField(help_text='Optional redundant string for action name (e.g. CONFIRMED)', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('phase_type', models.ForeignKey(blank=True, help_text='What kind of action (e.g. CONFIRMED, REFUSED, etc)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.phasetype')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'db_table': 'action_logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectLastStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_id', models.CharField(max_length=255, unique=True)),
                ('path_type', models.CharField(max_length=50)),
                ('latest_action', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('latest_phase_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.phasetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_last_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Last Object Status',
                'verbose_name_plural': 'Last Object Statuses',
                'db_table': 'object_last_status',
            },
        ),
    ]
