# Generated by Django 5.2.1 on 2025-05-31 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_actionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='identified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='identified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='notify_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notified_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
