# Generated by Django 5.2.1 on 2025-06-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_actionlog_identified_actionlog_identified_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderfile',
            name='original_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
