# Generated by Django 5.2.1 on 2025-06-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectfinancepart',
            unique_together={('project_code', 'fs_part_name')},
        ),
    ]
