# Generated by Django 5.2.1 on 2025-06-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_projectfinancepart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectlaststatus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
