# Generated by Django 5.2.1 on 2025-06-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_objectlaststatus_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectfinancepart',
            unique_together={('project_code', 'fs_part_no')},
        ),
    ]
