# Generated by Django 5.2.1 on 2025-06-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_projectfinancepart_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectfinancepart',
            unique_together={('project_code', 'fs_part_no', 'fs_part_name')},
        ),
    ]
