# Generated by Django 5.2.1 on 2025-06-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_projectfinancepart_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectfinancepart',
            unique_together={('project_code', 'fs_part_name'), ('project_code', 'fs_part_no')},
        ),
    ]
