# Generated by Django 5.2.1 on 2025-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_projectfinancepart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
