# Generated by Django 5.2.1 on 2025-06-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_workorder_finished_workorder_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_vocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_vocation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_vocation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_vocation_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='phone_number',
            field=models.CharField(default=998991234567, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffuser',
            name='pnfl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='position_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
