# Generated by Django 5.2.1 on 2025-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_staffuser_address_staffuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
