# Generated by Django 5.2.1 on 2025-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_staffuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile_image.png', null=True, upload_to='profile_images/'),
        ),
    ]
