# Generated by Django 5.2.1 on 2025-06-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_jobposition_alter_staffuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_positions', to='api.jobposition'),
        ),
    ]
