# Generated by Django 5.2.1 on 2025-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_jobposition_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='position_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='jobposition',
            unique_together={('department', 'position_name')},
        ),
    ]
