# Generated by Django 5.2.1 on 2025-06-21 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_jobposition_position_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, help_text='Any file type, max 300MB', null=True, upload_to='chat_files/%Y/%m/%d/')),
                ('file_original_name', models.CharField(blank=True, help_text='Original filename as uploaded by user', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['send_time'],
            },
        ),
    ]
