# Generated by Django 5.2.1 on 2025-06-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_chatmessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagefile',
            name='file_original_name',
            field=models.CharField(max_length=1000),
        ),
    ]
