# Generated by Django 5.2.1 on 2025-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_chatmessagefile_file_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagefile',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
