# Generated by Django 5.2.1 on 2025-06-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_usertask_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.usertask'),
            preserve_default=False,
        ),
    ]
