# Generated by Django 5.2.1 on 2025-06-24 03:48

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency_type',
            field=models.ForeignKey(blank=True, default=api.models.get_default_currency, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.currency'),
        ),
    ]
