# Generated by Django 5.2.1 on 2025-06-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_project_currency_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='currency_type',
            new_name='currency',
        ),
    ]
