# Generated by Django 5.2.1 on 2025-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_rename_currency_type_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='on_business_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_business_trip_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_business_trip_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_business_trip_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
