# Generated by Django 5.2.1 on 2025-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_staffuser_on_business_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
