# Generated by Django 5.2.1 on 2025-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_project_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='holded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='holded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='holded_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
