# Generated by Django 5.2.1 on 2025-06-25 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_workorder_holded_workorder_holded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='holded_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holded_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
