# Generated by Django 5.2.1 on 2025-06-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_workorder_holded_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='holded_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holded_fors', to=settings.AUTH_USER_MODEL),
        ),
    ]
