# Generated by Django 5.2.1 on 2025-06-30 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_workorder_holded_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
