# Generated by Django 5.2.1 on 2025-07-01 13:17

import api.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_staffuser_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('project_code', models.IntegerField(blank=True, db_index=True)),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True)),
                ('total_price', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('financier_confirm', models.BooleanField(default=False)),
                ('financier_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('gip_confirm', models.BooleanField(default=False)),
                ('gip_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, editable=False)),
                ('update_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('create_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, default=api.models.get_default_currency, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.currency')),
                ('financier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.partner')),
                ('project_gip', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Project',
                'verbose_name_plural': 'historical Projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
