# Generated by Django 5.2.1 on 2025-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_historicalproject_history_user_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='history_user_display',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='currency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='financier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='historicalproject',
            table='projects_hist',
        ),
    ]
