# Generated by Django 5.2.1 on 2025-07-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_project_history_user_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='create_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='project_gip_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
