# Generated by Django 5.2.1 on 2025-07-03 08:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_historicalproject_create_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProjectFinancePart',
            fields=[
                ('create_username', models.CharField(blank=True, max_length=150, null=True)),
                ('fs_part_code', models.IntegerField(blank=True, db_index=True)),
                ('fs_part_no', models.CharField(max_length=50)),
                ('fs_part_name', models.CharField(max_length=255)),
                ('fs_part_price', models.BigIntegerField()),
                ('fs_start_date', models.DateField()),
                ('fs_finish_date', models.DateField()),
                ('create_date', models.DateTimeField(blank=True, editable=False)),
                ('send_to_tech_dir', models.BooleanField(default=False)),
                ('send_to_tech_dir_date', models.DateTimeField(blank=True, null=True)),
                ('tech_dir_confirm', models.BooleanField(default=False)),
                ('tech_dir_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('create_user_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.project')),
            ],
            options={
                'verbose_name': 'historical Project Finance Part',
                'verbose_name_plural': 'historical Project Finance Parts',
                'db_table': 'pro_fin_part_hist',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
