# Generated by Django 5.2.1 on 2025-07-03 09:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_historicalprojectfinancepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProjectGipPart',
            fields=[
                ('create_username', models.CharField(blank=True, max_length=150, null=True)),
                ('tch_part_nach_username', models.CharField(blank=True, max_length=150, null=True)),
                ('history_user_display', models.CharField(blank=True, max_length=150, null=True)),
                ('tch_part_code', models.IntegerField(blank=True, db_index=True)),
                ('tch_part_no', models.CharField(max_length=50)),
                ('tch_part_name', models.CharField(max_length=255)),
                ('tch_start_date', models.DateField()),
                ('tch_finish_date', models.DateField()),
                ('create_date', models.DateTimeField(blank=True, editable=False)),
                ('nach_otd_confirm', models.BooleanField(default=False)),
                ('nach_otd_confirm_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('create_user_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fs_part_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.projectfinancepart')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tch_part_nach', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Technical Part',
                'verbose_name_plural': 'historical Technical Parts',
                'db_table': 'project_gip_parts_hist',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
