# Generated by Django 5.2.1 on 2025-07-03 09:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_historicalworkorderfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkOrder',
            fields=[
                ('tch_part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wo_staff_username', models.CharField(blank=True, max_length=150, null=True)),
                ('create_username', models.CharField(blank=True, max_length=150, null=True)),
                ('holded_for_username', models.CharField(blank=True, max_length=150, null=True)),
                ('history_user_display', models.CharField(blank=True, max_length=255, null=True)),
                ('wo_id', models.IntegerField(blank=True, db_index=True)),
                ('wo_no', models.IntegerField()),
                ('wo_name', models.CharField(max_length=255)),
                ('wo_start_date', models.DateField()),
                ('wo_finish_date', models.DateField()),
                ('create_date', models.DateTimeField(blank=True, editable=False)),
                ('staff_confirm', models.BooleanField(default=False)),
                ('wo_answer', models.TextField(blank=True, null=True)),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('wo_remark', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('holded', models.BooleanField(default=False)),
                ('holded_date', models.DateTimeField(blank=True, null=True)),
                ('holded_reason', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('create_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holded_for', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tch_part_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.projectgippart')),
                ('wo_staff', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Work Order',
                'verbose_name_plural': 'historical Work Orders',
                'db_table': 'work_order_hist',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
