# Generated by Django 5.2.1 on 2025-07-09 08:45

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_historicalworkorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStaffUsers',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_username', models.CharField(blank=True, max_length=150, null=True)),
                ('history_user_display', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('fio', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(blank=True, editable=False)),
                ('last_login_time_fail', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_image', models.TextField(blank=True, default='profile_images/default_profile_image.png', max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('on_vocation', models.BooleanField(default=False)),
                ('on_vocation_update', models.DateTimeField(blank=True, editable=False)),
                ('on_vocation_start', models.DateField(blank=True, null=True)),
                ('on_vocation_end', models.DateField(blank=True, null=True)),
                ('on_business_trip', models.BooleanField(default=False)),
                ('on_business_trip_update', models.DateTimeField(blank=True, editable=False)),
                ('on_business_trip_start', models.DateField(blank=True, null=True)),
                ('on_business_trip_end', models.DateField(blank=True, null=True)),
                ('pnfl', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('position_start_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('create_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, db_column='position_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.jobposition')),
                ('role', models.ForeignKey(blank=True, db_column='role_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.role')),
            ],
            options={
                'verbose_name': 'historical staff user',
                'verbose_name_plural': 'historical staff users',
                'db_table': 'staff_users_hist',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
