# Generated by Django 5.2.1 on 2025-07-10 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_historicalstaffusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstaffusers',
            name='on_medical_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstaffusers',
            name='on_medical_leave_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstaffusers',
            name='on_medical_leave_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstaffusers',
            name='on_medical_leave_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_medical_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_medical_leave_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_medical_leave_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='on_medical_leave_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
