# Generated by Django 5.2.1 on 2025-07-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_historicalstaffusers_on_medical_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
