version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: promont-backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8010
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - static_volume:/app/staticfiles
    expose:
      - "8010"
    ports:
      - "8010:8010"
    env_file:
      - ./backend/config/.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 1G

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: promont-nginx
    ports:
      - "4444:4444"
    volumes:
      - ./backend/media:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  static_volume:
