export const CONSTANTS = {
  FINANCIER_REFUSED: 'FINANCIER_REFUSED',
  FINANCIER_CONFIRMED: 'FINANCIER_CONFIRMED',
  TECH_DIR_REFUSED:'TECH_DIR_REFUSED',
  WORK_ORDER_FINISHED:'WORK_ORDER_FINISHED',
  WORK_ORDER_REFUSED_BY_NACH_OTDEL:'WORK_ORDER_REFUSED_BY_NACH_OTDEL',
  // Add other keys as needed
};
