// src/constants/permissions.js

export const PERMISSIONS = {
  CAN_CREATE_PROJECT: 'CAN_CREATE_PROJECT',
  CAN_VIEW:'CAN_VIEW',
  CAN_CONFIRM_PROJECT_FINANCIER:'CAN_CONFIRM_PROJECT_FINANCIER',
  CAN_CHECK_AND_GIP_ATTACH:'CAN_CHECK_AND_GIP_ATTACH',
  CAN_ADD_DEPARTMENTS:'CAN_ADD_DEPARTMENTS',
  CAN_ADD_PARTNERS:'CAN_ADD_PARTNERS',
};
