// src/constants/permissions.js

export const PERMISSIONS = {
  CAN_CREATE_PROJECT: 'CAN_CREATE_PROJECT',
  CAN_VIEW:'CAN_VIEW',
  CAN_CONFIRM_PROJECT_FINANCIER:'CAN_CONFIRM_PROJECT_FINANCIER',
  CAN_CHECK_AND_GIP_ATTACH:'CAN_CHECK_AND_GIP_ATTACH',
  CAN_ADD_DEPARTMENTS:'CAN_ADD_DEPARTMENTS',
  CAN_ADD_PARTNERS:'CAN_ADD_PARTNERS',
  CAN_MANAGE_TRANSLATIONS:'CAN_MANAGE_TRANSLATIONS',
  CAN_CREATE_TECH_PARTS:'CAN_CREATE_TECH_PARTS',
  CAN_CREATE_WORK_ORDER:'CAN_CREATE_WORK_ORDER',
  CAN_COMPLETE_WORK_ORDER:'CAN_COMPLETE_WORK_ORDER',
  CAN_CONFIRM_FINISHED_WORK_ORDER:'CAN_CONFIRM_FINISHED_WORK_ORDER',
  CAN_MANAGE_STAFF: 'CAN_MANAGE_STAFF',
  CAN_WORK_WITH_STAFF: 'CAN_WORK_WITH_STAFF',
  IS_ADMIN:'IS_ADMIN',
};
